### PR TITLE
all packets are separated into individual plugins

### PR DESCRIPTION
**Pull request by uzen**
<blockquote><p><b>some features:</b></p>
<p>including a file with functions:</p>
  \<import file="${basedir}/build.functions" as="std"/>
<br>
<p>faceunlock together with additional files</p>
   \<ant antfile="${optional.dir}/face-prebuild.xml"/>
</blockquote>

sorry, I forgot to move

### CODE REVIEW

**Comment by uzen** [comment]
http://www.mediafire.com/download/48i3v20qh9wo1cl/Slim_mini_gapps.5.x.x.build.000-20150501.zip

mini gapps

**Comment by raulx222** [comment]
Wow..pretty nice pull request :D

**Comment by raulx222** [comment]
Hmmm.. the installation doesn't stops at this step: `run_program("/system/addon.d/80-gapps.sh", "remove");` if the 80-gapps.sh doesn't exist?(if the package is installed on a clean ROM)
And also, you renamed the 80-gapps.sh to gapps.sh..and from updater-script the gapps.sh isn't executed for clean-up
And it's better to keep it 80-gapps.sh...the number represents the order of backup scripts execution when you install a ROM update.

**Comment by uzen** [comment]
check the contents of the package
system/addon.d

**Comment by uzen** [comment]
in the old 80-gapps missing that command  "remove"

**Comment by raulx222** [comment]
Yeap..but in your updater-script you run 80-gapps.sh with "remove"..that's what confuses me :D

**Pull request merged**
